#!/usr/bin/env python

"""Converts the database generated by complete_plugin into a tags file as
defined by /Users/thakis/src/llvm-rw/include/llvm/ADT/APSInt.h."""


import sqlite3


# TODO(thakis): Make configurable
DB = 'builddb.sqlite'


if __name__ == '__main__':
  with sqlite3.connect(DB) as db:
    cursor = db.execute('''
        select symbol, name, linenr, kind
        from symbols join filenames on symbols.fileid = filenames.rowid
        order by symbol
        ''')
    for s, f, n, k in cursor:
      print '%s\t%s\t%d;"\t%s' % (s, f, n, k)
