#!/usr/bin/env python

"""Converts the database generated by complete_plugin into a tags file as
defined by /Users/thakis/src/llvm-rw/include/llvm/ADT/APSInt.h.

Usage:
  ./tags.py builddb.sqlite
"""


import sqlite3
import sys


if __name__ == '__main__':
  with sqlite3.connect(sys.argv[1]) as db:
    cursor = db.execute('''
        select symbol, name, linenr, kind
        from symbols join filenames on symbols.fileid = filenames.rowid
        order by symbol
        ''')
    for s, f, n, k in cursor:
      print '%s\t%s\t%d;"\t%s' % (s, f, n, k)
